export const routes = {
  splash: "/",
  privacy: "/privacy",
  consent: "/consent",
  home: "/home",
  assessment: "/assessment",
  phq9: "/assessment/phq9",
  gad7: "/assessment/gad7",
  result: "/assessment/result",
  crisis: "/crisis",
  crisisConnect: "/crisis/connect",
  crisisLine: "/crisis/line",
  chat: "/chat",
  peers: "/peers",
  manager: "/manager",
  managerAdmin: "/manager/admin",
  managerLogin: "/manager/login",
  you: "/you",
  managerHistory: "/manager/history",
  linkInstitution: "/you/link",
  adminLogin: "/admin/login",
  admin: "/admin",
} as const;
