export const routes = {
  splash: "/",
  privacy: "/privacy",
  consent: "/consent",
  home: "/home",
  assessment: "/assessment",
  phq9: "/assessment/phq9",
  gad7: "/assessment/gad7",
  result: "/assessment/result",
  crisis: "/crisis",
  crisisConnect: "/crisis/connect",
  crisisLine: "/crisis/line",
  chat: "/chat",
  peers: "/peers",
  manager: "/manager",
  // Kept as a redirect to managerAdminManagers: the tabbed Administração page
  // it used to serve is gone, but links to it are not.
  managerAdmin: "/manager/admin",
  managerAdminManagers: "/manager/admin/managers",
  managerAdminSectors: "/manager/admin/sectors",
  managerAdminPeers: "/manager/admin/peers",
  managerNotifications: "/manager/notifications",
  managerSettings: "/manager/settings",
  managerLogin: "/manager/login",
  managerFinishSetup: "/manager/finish-setup",
  you: "/you",
  settings: "/settings",
  managerHistory: "/manager/history",
  linkInstitution: "/you/link",
  adminLogin: "/admin/login",
  admin: "/admin",
  peerPartnerLogin: "/peer/login",
  peerPartnerFinishSetup: "/peer/finish-setup",
  peerPartnerInbox: "/peer",
} as const;
